version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_POSTGRESDB_PORT=6543
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=postgres.luypvlpyrkvfwaaqwymq
      - DB_POSTGRESDB_PASSWORD=Dangtai@123
      - DB_POSTGRESDB_SSL=true
      - N8N_ENCRYPTION_KEY=YourSecretEncryptionKeyHere
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
    command: ["npm install n8n-nodes-zalo-tools && n8n"]

volumes:
  n8n_data:
